steps:
  - name: gcr.io/cloud-builders/npm
    args:
      - install
  - name: gcr.io/cloud-builders/npm
    args:
      - run
      - build
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '-t'
      - gcr.io/$_PROJECT_ID/my-app
      - .
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - gcr.io/$_PROJECT_ID/my-app
  # Deploy the built app to App Engine
  # note: App Engine expects image has app.yaml file in root specifying runtime
  #- name: 'gcr.io/cloud-builders/gcloud'
  #  args: ['app', 'deploy', '--image-url', 'gcr.io/$PROJECT_ID/my-image']
